# FlightGear multiplayer map
version: '3.4'

services:
  mpmap:
    image: flightgear/mpmap.js:latest
    build:
      context: .
    read_only: true
    environment:
      - "node_env=production"
      - "NODE_ENV=production"
    healthcheck:
      test: "curl -s http://localhost:8080/||exit 1"
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 2
    ports:
      - "8086:8080"
    volumes:
      - type: tmpfs
        target: /tmp
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 1m
      update_config:
        parallelism: 1
        delay: 10s

