# FlightGear multiplayer map
version: '3.2'

services:
  mpmap:
    image: registry.gitlab.com/t3r/mpmap/master:latest
    read_only: true
    environment:
      - "node_env=production"
      - "NODE_ENV=production"
#    healthcheck:
#      test: "wget -spider -q http://ui:8080/heath-check || exit 1"
#      interval: 30s
#      timeout: 10s
#      retries: 2
    ports:
      - "8086:8080"
    volumes:
      - type: tmpfs
        target: /tmp
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 1m
      update_config:
        parallelism: 1
        delay: 10s

